#!/bin/bash

# Advanced Multimodal Workflows
# This script demonstrates advanced usage patterns and complex scenarios

echo "=================================================="
echo "RAG-lite Advanced Multimodal Workflows"
echo "=================================================="
echo ""

# Workflow 1: Mode Migration
echo "=================================================="
echo "Workflow 1: Migrating from Text to Multimodal Mode"
echo "=================================================="
echo ""
echo "Scenario: You started with text mode but now want multimodal"
echo ""
echo "Step 1: Check current mode"
echo "  Your current database stores the mode used during ingestion"
echo "  Search automatically uses the correct mode"
echo ""
echo "Step 2: Re-ingest in multimodal mode"
echo "  Command: raglite ingest ./content/ --mode multimodal --model Xenova/clip-vit-base-patch32 --rebuild-if-needed"
echo ""
echo "  The --rebuild-if-needed flag will:"
echo "  • Detect the mode change"
echo "  • Rebuild the entire index"
echo "  • Re-embed all content with CLIP"
echo ""
echo "⚠️  Warning: This rebuilds the entire index!"
echo ""
echo "Step 3: Verify the migration"
echo "  Command: raglite search \"test query\" --content-type image"
echo "  If you get image results, migration was successful"
echo ""

# Workflow 2: Hybrid Content Organization
echo "=================================================="
echo "Workflow 2: Organizing Hybrid Content Collections"
echo "=================================================="
echo ""
echo "Scenario: You have mixed content that needs organization"
echo ""
echo "Directory structure:"
echo "  project/"
echo "  ├── docs/          # Text documentation"
echo "  ├── images/        # Visual assets"
echo "  ├── diagrams/      # Technical diagrams"
echo "  └── examples/      # Code examples"
echo ""
echo "Strategy 1: Ingest everything together"
echo "  Command: raglite ingest ./project/ --mode multimodal"
echo "  Pros: Single search across all content"
echo "  Cons: Larger index, slower ingestion"
echo ""
echo "Strategy 2: Selective ingestion"
echo "  Command: raglite ingest ./project/docs/ --mode text"
echo "  Command: raglite ingest ./project/images/ --mode multimodal"
echo "  Pros: Optimized for content type"
echo "  Cons: Requires multiple databases"
echo ""

# Workflow 3: Performance Optimization
echo "=================================================="
echo "Workflow 3: Performance Optimization Strategies"
echo "=================================================="
echo ""
echo "For large content collections, optimize performance:"
echo ""
echo "1. Choose the right reranking strategy"
echo "   Fast: --rerank-strategy disabled"
echo "   Balanced: --rerank-strategy metadata"
echo "   Quality: --rerank-strategy text-derived (default)"
echo ""
echo "2. Adjust top-k based on use case"
echo "   Quick preview: --top-k 3"
echo "   Standard: --top-k 10 (default)"
echo "   Comprehensive: --top-k 50"
echo ""
echo "3. Use content type filtering"
echo "   Reduces result processing time"
echo "   Command: raglite search \"query\" --content-type image --top-k 5"
echo ""
echo "4. Disable reranking for speed"
echo "   Command: raglite search \"query\" --no-rerank"
echo ""

# Workflow 4: Batch Processing
echo "=================================================="
echo "Workflow 4: Batch Processing Multiple Directories"
echo "=================================================="
echo ""
echo "Scenario: Ingest multiple directories efficiently"
echo ""
echo "Approach 1: Sequential ingestion"
cat << 'EOF'
#!/bin/bash
for dir in dir1 dir2 dir3; do
  echo "Ingesting $dir..."
  raglite ingest "./$dir/" --mode multimodal
done
EOF
echo ""
echo "Approach 2: Parallel ingestion (separate databases)"
cat << 'EOF'
#!/bin/bash
raglite ingest ./dir1/ --mode multimodal &
raglite ingest ./dir2/ --mode multimodal &
raglite ingest ./dir3/ --mode multimodal &
wait
EOF
echo ""
echo "⚠️  Note: Parallel ingestion requires separate database files"
echo ""

# Workflow 5: Content Validation
echo "=================================================="
echo "Workflow 5: Content Validation and Quality Checks"
echo "=================================================="
echo ""
echo "Validate your content after ingestion:"
echo ""
echo "1. Check text content coverage"
echo "   Command: raglite search \"*\" --content-type text --top-k 100"
echo "   Review: Are all expected documents present?"
echo ""
echo "2. Check image content coverage"
echo "   Command: raglite search \"*\" --content-type image --top-k 100"
echo "   Review: Are all expected images present?"
echo ""
echo "3. Test semantic search quality"
echo "   Command: raglite search \"specific concept\" --rerank"
echo "   Review: Are results relevant and well-ranked?"
echo ""
echo "4. Verify cross-modal connections"
echo "   Command: raglite search \"concept\" --content-type all"
echo "   Review: Do text and images relate semantically?"
echo ""

# Workflow 6: Incremental Updates
echo "=================================================="
echo "Workflow 6: Incremental Content Updates"
echo "=================================================="
echo ""
echo "Scenario: Add new content to existing index"
echo ""
echo "Step 1: Ingest new content"
echo "  Command: raglite ingest ./new-content/ --mode multimodal"
echo "  Note: Uses existing mode from database"
echo ""
echo "Step 2: Verify new content is searchable"
echo "  Command: raglite search \"new content topic\""
echo ""
echo "⚠️  Important: Mode must match existing database"
echo "  If database is in text mode, new ingestion uses text mode"
echo "  If database is in multimodal mode, new ingestion uses multimodal mode"
echo ""
echo "To change modes, use --rebuild-if-needed flag"
echo ""

# Workflow 7: Multi-Language Content
echo "=================================================="
echo "Workflow 7: Multi-Language Content Handling"
echo "=================================================="
echo ""
echo "CLIP models support multiple languages:"
echo ""
echo "Ingestion:"
echo "  Command: raglite ingest ./multilingual-content/ --mode multimodal"
echo "  Note: CLIP handles multiple languages automatically"
echo ""
echo "Searching:"
echo "  English: raglite search \"red car\""
echo "  Spanish: raglite search \"coche rojo\""
echo "  French: raglite search \"voiture rouge\""
echo ""
echo "Cross-language search works because:"
echo "  • CLIP embeddings are language-agnostic"
echo "  • Semantic meaning is preserved across languages"
echo "  • Images can be found with queries in any language"
echo ""

# Workflow 8: Error Recovery
echo "=================================================="
echo "Workflow 8: Error Recovery and Troubleshooting"
echo "=================================================="
echo ""
echo "Common issues and solutions:"
echo ""
echo "Issue 1: Model mismatch error"
echo "  Error: 'Dimension mismatch detected'"
echo "  Solution: raglite ingest ./content/ --rebuild-if-needed"
echo ""
echo "Issue 2: Corrupted index"
echo "  Error: 'Vector index error'"
echo "  Solution: raglite rebuild"
echo ""
echo "Issue 3: No results found"
echo "  Check 1: Verify content was ingested"
echo "  Check 2: Try broader search terms"
echo "  Check 3: Remove content type filter"
echo "  Command: raglite search \"query\" --content-type all"
echo ""
echo "Issue 4: Poor result quality"
echo "  Solution 1: Enable reranking"
echo "  Command: raglite search \"query\" --rerank"
echo "  Solution 2: Increase top-k"
echo "  Command: raglite search \"query\" --top-k 20"
echo ""

# Workflow 9: Integration with Other Tools
echo "=================================================="
echo "Workflow 9: Integration with Other Tools"
echo "=================================================="
echo ""
echo "RAG-lite CLI can be integrated into larger workflows:"
echo ""
echo "1. Shell scripts and automation"
cat << 'EOF'
#!/bin/bash
# Automated content ingestion pipeline
find ./content -type f -newer .last-ingest | while read file; do
  raglite ingest "$file" --mode multimodal
done
touch .last-ingest
EOF
echo ""
echo "2. CI/CD pipelines"
cat << 'EOF'
# .github/workflows/ingest.yml
- name: Ingest documentation
  run: |
    raglite ingest ./docs/ --mode text
    raglite search "test" --top-k 1  # Verify
EOF
echo ""
echo "3. Monitoring and alerting"
cat << 'EOF'
#!/bin/bash
# Check search quality
results=$(raglite search "critical term" --top-k 1)
if [ -z "$results" ]; then
  echo "Alert: No results for critical term!"
fi
EOF
echo ""

# Workflow 10: Best Practices Summary
echo "=================================================="
echo "Workflow 10: Best Practices Summary"
echo "=================================================="
echo ""
echo "✓ Choose the right mode for your content"
echo "  Text mode: Text-only content, faster ingestion"
echo "  Multimodal mode: Mixed content, cross-modal search"
echo ""
echo "✓ Optimize for your use case"
echo "  Speed: --rerank-strategy disabled --no-rerank"
echo "  Quality: --rerank-strategy text-derived --rerank"
echo "  Balance: --rerank-strategy metadata"
echo ""
echo "✓ Use descriptive filenames"
echo "  Good: red-sports-car-city-street.jpg"
echo "  Bad: IMG_1234.jpg"
echo ""
echo "✓ Organize content logically"
echo "  Use directory structure to group related content"
echo "  Makes ingestion and management easier"
echo ""
echo "✓ Test search quality regularly"
echo "  Run test queries after ingestion"
echo "  Verify results are relevant"
echo "  Adjust reranking strategy if needed"
echo ""
echo "✓ Monitor index size and performance"
echo "  Large indexes may need optimization"
echo "  Consider splitting into multiple databases"
echo "  Use content type filtering for faster searches"
echo ""
echo "✓ Keep backups of your database"
echo "  Database file: db.sqlite"
echo "  Index file: vector-index.bin"
echo "  Backup before major changes"
echo ""

# Real-world example
echo "=================================================="
echo "Real-World Example: E-commerce Product Search"
echo "=================================================="
echo ""
echo "Scenario: Build a product search system"
echo ""
echo "Step 1: Organize product data"
echo "  products/"
echo "  ├── descriptions/  # Product descriptions (text)"
echo "  └── images/        # Product photos (images)"
echo ""
echo "Step 2: Ingest in multimodal mode"
echo "  Command: raglite ingest ./products/ --mode multimodal --model Xenova/clip-vit-base-patch32"
echo ""
echo "Step 3: Enable metadata reranking for speed"
echo "  Command: raglite ingest ./products/ --mode multimodal --rerank-strategy metadata"
echo ""
echo "Step 4: Test search scenarios"
echo "  Text query: raglite search \"red leather jacket\" --top-k 10"
echo "  Image only: raglite search \"red leather jacket\" --content-type image --top-k 5"
echo "  With reranking: raglite search \"red leather jacket\" --rerank --top-k 10"
echo ""
echo "Step 5: Monitor and optimize"
echo "  • Track search performance"
echo "  • Adjust top-k based on user behavior"
echo "  • Update reranking strategy if needed"
echo ""

echo "=================================================="
echo "Advanced Workflows Complete!"
echo "=================================================="
echo ""
echo "You now have the knowledge to:"
echo "  ✓ Migrate between modes"
echo "  ✓ Organize hybrid content collections"
echo "  ✓ Optimize for performance"
echo "  ✓ Handle batch processing"
echo "  ✓ Validate content quality"
echo "  ✓ Manage incremental updates"
echo "  ✓ Work with multi-language content"
echo "  ✓ Recover from errors"
echo "  ✓ Integrate with other tools"
echo "  ✓ Apply best practices"
echo ""
echo "For more information:"
echo "  • docs/cli-reference.md - Complete CLI reference"
echo "  • docs/multimodal-tutorial.md - Detailed tutorial"
echo "  • docs/troubleshooting.md - Common issues and solutions"
echo ""
