#!/bin/bash

# Content Type Filtering Examples
# This script demonstrates how to filter search results by content type

echo "=================================================="
echo "RAG-lite Content Type Filtering Examples"
echo "=================================================="
echo ""

echo "Overview"
echo "--------"
echo ""
echo "The --content-type option allows you to filter search results:"
echo "  • text: Show only text documents"
echo "  • image: Show only images"
echo "  • all: Show all content types (default)"
echo ""
echo "This is useful when you want specific types of results."
echo ""

# Example 1: Filter to text only
echo "=================================================="
echo "Example 1: Text-Only Results"
echo "=================================================="
echo ""
echo "Scenario: You want documentation, not images"
echo ""
echo "Command: raglite search \"machine learning\" --content-type text"
echo ""
echo "Use cases:"
echo "  • Finding documentation and articles"
echo "  • Searching code comments and README files"
echo "  • Locating written explanations"
echo ""

raglite search "machine learning" --content-type text

echo ""
echo "✓ Filtered to show only text documents"
echo ""

# Example 2: Filter to images only
echo "=================================================="
echo "Example 2: Image-Only Results"
echo "=================================================="
echo ""
echo "Scenario: You need visual content only"
echo ""
echo "Command: raglite search \"red vehicle\" --content-type image"
echo ""
echo "Use cases:"
echo "  • Finding photos and illustrations"
echo "  • Searching visual assets"
echo "  • Locating diagrams and charts"
echo ""

raglite search "red vehicle" --content-type image

echo ""
echo "✓ Filtered to show only images"
echo ""

# Example 3: All content types (default)
echo "=================================================="
echo "Example 3: All Content Types (Default)"
echo "=================================================="
echo ""
echo "Scenario: You want comprehensive results"
echo ""
echo "Command: raglite search \"ocean\" --content-type all"
echo ""
echo "Or simply: raglite search \"ocean\""
echo ""
echo "Use cases:"
echo "  • Exploratory searches"
echo "  • Finding all related content"
echo "  • Discovering unexpected connections"
echo ""

raglite search "ocean" --content-type all

echo ""
echo "✓ Showing all content types"
echo ""

# Example 4: Combining with other options
echo "=================================================="
echo "Example 4: Combining Filters with Other Options"
echo "=================================================="
echo ""
echo "You can combine --content-type with other options:"
echo ""

echo "Example 4a: Top-K with content type filter"
echo "Command: raglite search \"nature\" --content-type image --top-k 3"
echo ""
raglite search "nature" --content-type image --top-k 3
echo ""

echo "Example 4b: Reranking with content type filter"
echo "Command: raglite search \"sports car\" --content-type text --rerank"
echo ""
raglite search "sports car" --content-type text --rerank
echo ""

echo "Example 4c: All options combined"
echo "Command: raglite search \"mountain\" --content-type image --top-k 5 --rerank"
echo ""
raglite search "mountain" --content-type image --top-k 5 --rerank
echo ""

# Example 5: Understanding the output
echo "=================================================="
echo "Example 5: Understanding Filtered Output"
echo "=================================================="
echo ""
echo "When filtering is applied, you'll see:"
echo ""
echo "1. Filter notification (if results were filtered):"
echo "   'Filtered to X image results (from Y total)'"
echo ""
echo "2. Content type indicators in results:"
echo "   📄 [TEXT] - Text documents"
echo "   🖼️  [IMAGE] - Image files"
echo ""
echo "3. Different information based on type:"
echo "   Text: Shows content preview"
echo "   Images: Shows description, dimensions, format"
echo ""

# Practical workflows
echo "=================================================="
echo "Practical Filtering Workflows"
echo "=================================================="
echo ""

echo "Workflow 1: Progressive Refinement"
echo "-----------------------------------"
echo "1. Start broad: raglite search \"cars\""
echo "2. Refine to images: raglite search \"cars\" --content-type image"
echo "3. Add more filters: raglite search \"cars\" --content-type image --top-k 3"
echo ""

echo "Workflow 2: Parallel Searches"
echo "------------------------------"
echo "Search both content types separately for comparison:"
echo "1. Text search: raglite search \"ocean\" --content-type text"
echo "2. Image search: raglite search \"ocean\" --content-type image"
echo "3. Compare results to understand content coverage"
echo ""

echo "Workflow 3: Content Discovery"
echo "------------------------------"
echo "1. Find all content: raglite search \"topic\""
echo "2. Identify content gaps by type"
echo "3. Filter to missing type for targeted search"
echo ""

# Use case examples
echo "=================================================="
echo "Use Cases for Content Type Filtering"
echo "=================================================="
echo ""

echo "1. Documentation Search (--content-type text)"
echo "   • Finding API documentation"
echo "   • Searching technical guides"
echo "   • Locating configuration examples"
echo "   Example: raglite search \"API authentication\" --content-type text"
echo ""

echo "2. Visual Asset Search (--content-type image)"
echo "   • Finding product photos"
echo "   • Searching design mockups"
echo "   • Locating diagrams and charts"
echo "   Example: raglite search \"user interface design\" --content-type image"
echo ""

echo "3. Comprehensive Research (--content-type all)"
echo "   • Academic research"
echo "   • Content audits"
echo "   • Knowledge discovery"
echo "   Example: raglite search \"climate change\" --content-type all"
echo ""

echo "4. Quality Assurance"
echo "   • Verify content coverage by type"
echo "   • Check for missing visual assets"
echo "   • Ensure documentation completeness"
echo "   Example: raglite search \"feature X\" --content-type text"
echo "            raglite search \"feature X\" --content-type image"
echo ""

# Performance considerations
echo "=================================================="
echo "Performance Considerations"
echo "=================================================="
echo ""
echo "Filtering happens after search, so:"
echo ""
echo "✓ Filtering is fast (client-side operation)"
echo "✓ No impact on search performance"
echo "✓ Can change filter without re-searching"
echo ""
echo "⚠️  Note: Filtering reduces result count"
echo "   If you filter to images and there are only 2 image results,"
echo "   you'll get 2 results even if --top-k 10 is specified."
echo ""

# Tips and best practices
echo "=================================================="
echo "Tips for Effective Content Type Filtering"
echo "=================================================="
echo ""
echo "✓ Use text filter for documentation searches"
echo "  - Faster to scan text results"
echo "  - Better for finding specific information"
echo "  - Ideal for code and configuration searches"
echo ""
echo "✓ Use image filter for visual searches"
echo "  - Focus on visual content only"
echo "  - Better for design and asset searches"
echo "  - Ideal for finding diagrams and photos"
echo ""
echo "✓ Use all (default) for exploratory searches"
echo "  - Discover unexpected connections"
echo "  - Get comprehensive view of content"
echo "  - Useful for initial research"
echo ""
echo "✓ Combine with top-k for focused results"
echo "  - --content-type image --top-k 3"
echo "  - Get just the most relevant images"
echo "  - Faster review of results"
echo ""
echo "✓ Use reranking for better quality"
echo "  - --content-type text --rerank"
echo "  - Improves ranking accuracy"
echo "  - Worth the extra processing time"
echo ""

echo "=================================================="
echo "Content Type Filtering Examples Complete!"
echo "=================================================="
echo ""
echo "Key Takeaways:"
echo "  • --content-type filters results by type"
echo "  • Three options: text, image, all (default)"
echo "  • Filtering is fast and client-side"
echo "  • Combine with other options for powerful searches"
echo ""
echo "Next Steps:"
echo "  • Try filtering with your own content"
echo "  • Experiment with different combinations"
echo "  • Explore advanced-workflows.sh for complex scenarios"
echo ""
